# -*- coding: utf-8 -*-
"""extraer_resumen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qh2E1jaV1VHNTCUiIIvhI95I-DeJpU43
"""

####
### USAR TPU

# import threading
# import subprocess
# import time
# import requests
import os
from collections import Counter
#from nltk import word_tokenize
from nltk.tokenize import word_tokenize

#!pip install PyPDF2 langchain_core langchain_ollama



# from PyPDF2 import PdfReader
# from langchain_core.prompts import ChatPromptTemplate
# from langchain_ollama.llms import OllamaLLM

#from google.colab import drive
#drive.mount('/content/drive')

# path donde se encuentran los archivos pdf
#pdf_path = '/content/drive/My Drive/Funiber/Notebook/pdfs'

# resumen de un PDF usando modelo deepseek-r1 de Ollama
# def summarize_pdf_with_ollama(pdf_path: str) -> str:
#     text = ""
#     try:
#         with open(pdf_path, 'rb') as file:
#             reader = PdfReader(file)
#             for page in reader.pages:
#                 text += page.extract_text() if page.extract_text() else ""
#     except Exception as e:
#         return f"Error reading PDF {pdf_path}: {e}"

#     if not text.strip():
#         return "No extractable text found in the PDF."

#     # Instancia Ollama LLM
#     model = OllamaLLM(model="deepseek-r1")

#     # Definir el prompt para pedir el resumen
#     prompt_template = ChatPromptTemplate.from_template("""Realiza un resumen del siguiente documento, enfocándote solo en las ideas principales. Puedes
#     basarte en la sección Introducción, Resultados y Conclusiones (si las hubiere).
#     Tu resumen no debe exceder las 250 palabras y debe estar escrito con estilo académico. No incluyas títulos ni subtítulos. 
#     No resaltes algunas palabras con "*" o "#".
#     No comiences tu resumen con frases como "el texto ....", "el trabajo ...", "el presente trabajo ...", "esta investigación ...", o frases similares, tampoco con frases informales.
#     No comiences saludando o haciendo preguntas. Al finalizar, no ofrezcas otra ayuda ni saludes. 
#     Escribe un resumen muy formal, con estilo académico, y en idioma español.

#     Documento: {document}

#     Resumen:
#     """)

#     # Crear una cadena para procesar
#     chain = prompt_template | model

#     # Invocar al modelo
#     summary = chain.invoke({"document": text})

#     return summary.strip()

# def run_ollama_serve():
#     # Check if the executable exists
#     if not os.path.exists(OLLAMA_EXECUTABLE_PATH):
#         print(f"Error: '{OLLAMA_EXECUTABLE_PATH}' not found. Please ensure Ollama is installed correctly.")
#         return # Exit the thread if ollama is not found

#     # Using the full path to ollama
#     proc = subprocess.Popen([OLLAMA_EXECUTABLE_PATH, "serve"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, preexec_fn=os.setsid)
#     print(line.decode().strip())

    
# si el resumen tiene pocas palabras generar un resumen más extenso    
def extraer_pal_resumen(df, pdf_path):
# Ensure Ollama is installed at the beginning of the cell execution
# !curl -fsSL https://ollama.ai/install.sh | sh

# # Explicitly define the path to the ollama executable
# OLLAMA_EXECUTABLE_PATH = "/usr/local/bin/ollama"    
#     thread = threading.Thread(target=run_ollama_serve)
#     thread.start()

#     # Wait for Ollama server to start. Add a robust check.
#     max_retries = 20 # Increased retries as it can take some time
#     for i in range(max_retries):
#         try:
#             response = requests.get("http://127.0.0.1:11434")
#             if response.status_code == 200:
#                 print("Ollama server is running.")
#                 break
#         except requests.exceptions.ConnectionError:
#             print(f"Waiting for Ollama server to start (attempt {i+1}/{max_retries})...")
#             time.sleep(5)
#     else:
#         print("Ollama server did not start in time. Please check the setup.")
#         raise SystemExit("Ollama server failed to start.")

#     # Pull the deepseek-r1 model again to ensure it's fully downloaded and ready
#     print("Pulling deepseek-r1 model...")
#     if not os.path.exists(OLLAMA_EXECUTABLE_PATH):
#         print(f"Error: '{OLLAMA_EXECUTABLE_PATH}' not found for pulling model.")
#     else:
#         pull_process = subprocess.run([OLLAMA_EXECUTABLE_PATH, "pull", "deepseek-r1"], capture_output=True, text=True)
#         if pull_process.returncode == 0:
#             print("deepseek-r1 model pulled.")
#         else:
#             print(f"Error pulling deepseek-r1 model: {pull_process.stderr}")

#     if not os.path.exists(pdf_path):
#         print(f"Error: La carpeta '{pdf_path}' no existe. Verificar en Google Drive, o ejecutar la celda anterior.")
#     else:
#         all_files_and_dirs = os.listdir(pdf_path)

    # resumir solo los trabajos con pocas palabras en el resumen    
    # for reg in df:
    #     print(reg)
    #     tokens = word_tokenize(reg['resumen'])  #separa el texto en tokens
    #     cant_palabras = len([w for w in tokens if w.isalnum()])   #cuenta la cantidade palabras (sin símbolos)
    #     if cant_palabras<100:
    #         #extraer un resumen y reemplazar
    #         print(str(cant_palabras)+' '+df['id'])
    #         df['resumen'] = cant_palabras
            
    #         #buscar archivo
    #         pdf_file_path = os.path.join(pdf_path, df['pdf'])
    #         if pdf_file_path.lower().endswith('.pdf'):
    #             print(f"Resumiendo {filename}...")
    #             summary_text = summarize_pdf_with_ollama(pdf_file_path)
    #             df['resumen'] = summary_text
    #             df['resumen']= str(cant_palabras)+'  resumido'
    #             print(df['id']+ '  extraido el resumen')
                

    for i in range(len(df)):
        reg=df.loc[i]
        tokens = word_tokenize(reg['resumen'])  #separa el texto en tokens
        cant_palabras = len([w for w in tokens if w.isalnum()])   #cuenta la cantidade palabras (sin símbolos)
        print(str(cant_palabras)+" "+str(reg['id']))
        if cant_palabras<100:
            print(str(cant_palabras)+" "+str(reg['id']))
            #extraer un resumen de pdf y reemplazar
            filename = str(reg['pdf'])
            name = filename.split("/")[-1]
            pdf_file_path = os.path.join(pdf_path, str(filename))
            
            if pdf_file_path.lower().endswith('.pdf'):
                print(f"Resumiendo {name}...")
                summary_text = name   #####    esto VA: summarize_pdf_with_ollama(pdf_file_path)
                df.iloc[i]['resumen'] = summary_text  
    return df


